
version: "3"
services:
  node-app-container:
    build: . 
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/content
    env_file:
      - ./.env
    expose:
      - '8001'
    ports:
      - '8001:8001'
    command: npm run dev